lab50:
  files:
    - lexicon.py
    - lyrics/drake.txt
    - lyrics/eminem.txt
    - lyrics/jay-z.txt
    - lyrics/jurassic 5.txt
    - lyrics/kanye.txt
    - lyrics/kendrick.txt
    - lyrics/outkast.txt
