lab50:
  window:
    - editor
    - readme
    - terminal
  files:
    - include! lexicon.py
    - include! lyrics/drake.txt
    - include! lyrics/eminem.txt
    - include! lyrics/jay-z.txt
    - include! lyrics/jurassic 5.txt
    - include! lyrics/kanye.txt
    - include! lyrics/kendrick.txt
    - include! lyrics/outkast.txt
